import './style.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000', WS=import.meta.env.VITE_WS_URL||'ws://localhost:8000';
let token=localStorage.getItem('airnet_token'), refresh=localStorage.getItem('airnet_refresh'), user=null, room=null, socket=null;
const app=document.querySelector('#app');
const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#92;'}[c]));
async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}}); if(!r.ok) throw new Error((await r.json().catch(()=>({detail:'Request failed'}))).detail); return r.json()}
function auth(){app.innerHTML=`<main class="auth"><section><div class="logo">✈ AIRNET</div><h1>Talk without limits.</h1><p>Realtime rooms, chat and voice-ready communication.</p><form id="auth"><input name="username" placeholder="Username" minlength="3" required><input name="email" type="email" placeholder="Email" required><input name="password" type="password" placeholder="Password (8+ chars)" minlength="8" required><button>CREATE ACCOUNT</button><button type="button" id="switch">Already have an account →</button></form></section></main>`;let reg=true;document.querySelector('#switch').onclick=()=>{reg=!reg;document.querySelector('[name=username]').style.display=reg?'block':'none';document.querySelector('#auth button').textContent=reg?'CREATE ACCOUNT':'SIGN IN';document.querySelector('#switch').textContent=reg?'Already have an account →':'Create an account →'};document.querySelector('#auth').onsubmit=async e=>{e.preventDefault();let x=Object.fromEntries(new FormData(e));try{let d=await api(reg?'/auth/register':'/auth/login',{method:'POST',body:JSON.stringify(reg?x:{email:x.email,password:x.password})});token=d.access_token;refresh=d.refresh_token;localStorage.setItem('airnet_token',token);localStorage.setItem('airnet_refresh',refresh);load()}catch(err){alert(err.message)}}}
async function load(){try{user=await api('/users/me')}catch{token=null;return auth()}const rooms=await api('/rooms');app.innerHTML=`<div class="shell"><aside><div class="brand">✈ Airnet</div><div class="me">● ${esc(user.username)}<small>${esc(user.email)}</small></div><div class="side-title">YOUR ROOMS <button id="new">＋</button></div><div id="rooms">${rooms.map(r=>`<button class="room" data-id="${r.id}"># ${esc(r.name)}</button>`).join('')}</div><button id="logout" class="logout">Sign out</button></aside><main class="chat"><header><div><strong id="title">Select a room</strong><span id="status">Realtime</span></div><button id="voice">🎙 Voice</button></header><div id="messages" class="messages"><div class="empty">Create or join a room to start chatting.</div></div><form id="send" class="composer"><input id="input" placeholder="Message Airnet…" autocomplete="off"><button>Send</button></form></main></div>`;document.querySelectorAll('.room').forEach(b=>b.onclick=()=>openRoom(b.dataset.id));document.querySelector('#new').onclick=async()=>{let n=prompt('Room name');if(n){await api('/rooms',{method:'POST',body:JSON.stringify({name:n,is_private:false})});load()}};document.querySelector('#logout').onclick=()=>{localStorage.clear();location.reload()};document.querySelector('#send').onsubmit=e=>{e.preventDefault();if(socket?.readyState===1&&input.value.trim()){socket.send(JSON.stringify({type:'chat_message',content:input.value}));input.value=''}}}
async function openRoom(id){room=id;const list=await api(`/rooms/${id}/messages`);messages.innerHTML=list.map(m=>`<article><b>${esc(m.username)}</b><time>${new Date(m.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time><p>${esc(m.content)}</p></article>`).join('')||'<div class="empty">No messages yet. Say hello 👋</div>';const r=(await api('/rooms')).find(x=>x.id===id);title.textContent='# '+r.name;socket?.close();socket=new WebSocket(`${WS}/ws/rooms/${id}?token=${encodeURIComponent(token)}`);socket.onopen=()=>status.textContent='● Connected';socket.onclose=()=>status.textContent='Offline';socket.onmessage=e=>{const d=JSON.parse(e.data);if(d.type==='chat_message'){const p=d.payload;messages.insertAdjacentHTML('beforeend',`<article><b>You</b><time>${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time><p>${esc(p.content)}</p></article>`);messages.scrollTop=messages.scrollHeight}}}
load();
